# Basic USB configuration
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y

# Debug settings
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_KSCAN_LOG_LEVEL_DBG=y
CONFIG_ZMK_USB_LOG_LEVEL_DBG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y

# Display settings
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_LVGL_USE_CONT=y
CONFIG_LVGL_USE_IMG=y