# Basic USB configuration
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y

# Disable display
CONFIG_ZMK_DISPLAY=n

# Debug settings
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_KSCAN_LOG_LEVEL_DBG=y
CONFIG_ZMK_USB_LOG_LEVEL_DBG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y