CONFIG_ZMK_DISPLAY=y
CONFIG_NICE_VIEW=y
CONFIG_NICE_VIEW_WIDGET_STATUS=y

# Disable the default widgets to prevent conflicts
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
CONFIG_ZMK_WIDGET_LAYER_STATUS=n